### ISSUE TITLE
About the formula 3 in the paper.

### ISSUE THREAD

**Issue by Qi-HuT** [nayeemrizve/ups#1]
Whether the first y in the formula is a hard pseudo-label generated by the network prediction.

![image](https://user-images.githubusercontent.com/46215418/115996086-dd783280-a618-11eb-8e48-f50476abef61.png)

**Comment by nayeemrizve** [comment]
Yes

**Comment by Sun-Rider** [comment]
So in [here](https://github.com/nayeemrizve/ups/blob/f3b49ace801a223e33e3b822a5137e20adce93dc/utils/train_util.py#L50), why you only use 1 instead of (1-sim y). 

Do I miss something?
