### ISSUE TITLE
Don't use view in accuracy calc

### ISSUE THREAD

**Issue by njhurst** [nayeemrizve/ups#2]
training crashed in the accuracy test code at:
```
  File "/home/njh/torchtoys/ups/utils/misc.py", line 41, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```
changing to reshape(-1) appears to have fixed it.

**Comment by nayeemrizve** [comment]
Thank you for your feedback. I believe we used an older version of torch (probably 1.3.x). Therefore, .view(.) worked fine and we didn't notice this bug before.

**Comment by xiaoliwang-717** [comment]
hi~I find a conflict between the torch and torchvision versions. You sure it's right?

**Comment by nayeemrizve** [comment]
> hi~I find a conflict between the torch and torchvision versions. You sure it's right?

I have updated the README and requirements file with the correct version.
