### ISSUE TITLE
About the relationship between prediction uncertainty and expected calibration error (ECE)

### ISSUE THREAD

**Issue by chengjianhong** [nayeemrizve/ups#6]
Hi, can you tell me how to do draw Fig.1(a)? I know a sample has an uncertainty for a model. But how to calculate the ECE for a sample? I understand that the ECE is for the whole data.

**Comment by nayeemrizve** [comment]
Hello, thank you for expressing interest in our work. For drawing Figure 1(a), we have selected subsets with different uncertainty thresholds (x-axis) and computed the ECE score for that particular subset (y-axis).

**Comment by leodmel** [comment]
I have the same question as well, can we say the x axis in figure 1a represents the percentage of data selected? e.g. Uncertainty (STD) = 0.4 means 40% of data are selected after applying some threshold to predicted probability (softmax output)? What does STD stand for by the way?
